### ISSUE TITLE
How to use TL-moments in RStudio

### ISSUE THREAD

**Issue by muhdnuru** [jorenham/Lmo#338]
We need to have the code of TL-moments that will be used to install in R-studio because it is not available. already L-moments was installed in R-studio.
Thanks in anticipating your timely response.

**Comment by jorenham** [comment]
I'm don't have experience with RStudio. But since Lmo is a Python package, you are going to need to use [reticulate](https://github.com/rstudio/reticulate/) to install Lmo via [PyPI](https://pypi.org/project/lmo/) (so not conda).

In case you haven't already, [this guide](https://docs.posit.co/ide/user/ide/guide/environments/py/python.html) outlines how you can get started with Python in RStudio.
Reticulate also has a guide on how to install PyPI packages: https://rstudio.github.io/reticulate/articles/python_packages.html

In case this doesn't solve it for you, please provide the exact commands or code that you used to install Lmo, the exact error output, which OS you are using, and the relevant versions of RStudio and Python.

**Comment by muhdnuru** [comment]
Sorry Sir, it is not L-moments I'm having issues but it's TL-MOMENTS when I
was trying to install it in R-studio. When I was checking devtools I came
across you with the codes, so can you get me with a code so that I can
proceed with installation.
Thanks

**Comment by muhdnuru** [comment]
I have already installed lmo, what I was trying is TL-MOMENTS Sir. I need
to get the code of TL-MOMENTS to run it in R-studio.
Thanks

**Comment by jorenham** [comment]
> I have already installed lmo, what I was trying is TL-MOMENTS Sir. I need to get the code of TL-MOMENTS to run it in R-studio. Thanks

So assuming that you're talking about sample TL-moments, then instead of calling e.g. `lmo.l_moment(my_data, 2)` to calculate the 2nd L-moment, you call `lmo.l_moment(my_data, 2, trim=1)`. That will give you the (2nd) TL-moment.

**Comment by muhdnuru** [comment]
So there is no need for installation of TL-MOMENTS since I already have an
lmom, I can use lmo.l_moment(my_data,2,  trim=1). To get the results of
TL-MOMENTS.
If I get you right.
Thanks

**Comment by jorenham** [comment]
I don't know what you mean with "the code of TL-moments". 

`Lmo` is an open-source Python library that implements both L-moments and TL-moments. 
Is that what you are trying to install?

**Comment by muhdnuru** [comment]
Awesome, thanks for the update!
